on:
  pull_request_target:
    types: [opened, synchronize]
jobs:
  comment-allure:
    runs-on: ubuntu-latest
    if: github.actor == 'DuLLey-vz'
    steps:
      - name: Comment Allure report link
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `ðŸ“Š **Allure Report publicado com sucesso**  
            ðŸ‘‰ https://dulley-vz.github.io/allure-test-video-duley/`
            })
