name: Pytest + Allure Report to Summary

on:
  push:
    branches: [main]

  pull_request:
    branches: []

permissions:
  contents: read

jobs:
  tests:
    name: CI Tests âœ… | ðŸ“Š Allure Report to Summary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      # âœ… Forma correta no Ubuntu 24.04
      - name: Install Playwright Browsers
        run: playwright install --with-deps

      - name: Run tests
        run: |
          mkdir -p allure-results
          pytest -vv --alluredir=allure-results

      - name: Install Allure CLI
        if: always()
        run: |
          if ! command -v allure &> /dev/null; then
            npm install -g allure-commandline
          fi

      - name: Restore Allure history
        if: always()
        uses: actions/cache@v4
        with:
          path: allure-results/history
          key: allure-history

      - name: Generate Allure report
        if: always()
        run: allure generate allure-results -o allure-report

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results/

      - name: Define report version
        if: always()
        run: |
          echo "REPORT_VERSION=runs/${{ github.run_id }}" >> $GITHUB_ENV

      # # ðŸ”— Summary (para DuLLey e ZhOWzz)
      # - name: Publish Allure Report link to Summary
      #   if: always()
      #   run: |
      #     echo "## ðŸ“Š Allure Report" >> $GITHUB_STEP_SUMMARY
      #     echo "" >> $GITHUB_STEP_SUMMARY
      #     echo "ðŸ‘‰ **RelatÃ³rio disponÃ­vel:**" >> $GITHUB_STEP_SUMMARY
      #     echo "" >> $GITHUB_STEP_SUMMARY
      #     echo "ðŸ”— https://dulley-vz.github.io/allure-test-video-duley/" >> $GITHUB_STEP_SUMMARY

      - name: Publish Allure link in Summary
        if: always()
        run: |
          echo "## ðŸ“Š Allure Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "ðŸ”— https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.run_id }}/" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "_RelatÃ³rio exclusivo desta execuÃ§Ã£o (sem cache)_" >> $GITHUB_STEP_SUMMARY
